# version: 0.0
# os: linux

# files:
#   - source: /
#     destination: /home/ubuntu/chagok
#     overwrite: yes
# permissions:
#   - object: /home/ubuntu/chagok
#     owner: ubuntu
#     group: ubuntu
#     mode: 755
# hooks:
#   BeforeInstall:
#     - location: scripts/before-install.sh
#       timeout: 300
#       runas: root
#   AfterInstall:
#     - location: scripts/after-install.sh
#       timeout: 300
#       runas: root