import type { Metadata } from "next";
import Providers from "@/utils/provider/react-query-provider";

import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Dear",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en" className={inter.className}>
        <Providers>{children}</Providers>
      </html>
  );
}
